---

name: CompileCheck

on: [push]

jobs:
  compile:
    name: ${{ matrix.cenv.runs-on }}-${{ matrix.cenv.cc }}
    strategy:
      matrix:
        cenv:
          - { runs-on: ubuntu-20.04, cc: gcc-9 }
          - { runs-on: ubuntu-20.04, cc: gcc-10 }
    runs-on: ${{ matrix.cenv.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          # This is needed as the version.sh script uses
          # the history.
          fetch-depth: 0
      - run: |
          bash -x build/init_autotools.sh
          mkdir -p COMPILE
          cd COMPILE
          CC=${{ matrix.cenv.cc }} ../configure
          make
        shell: bash
